wandb_version: 1

epochs:
  desc: null
  value:
  - 5
  - 10
  - 20
learning_rate:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686843540.510851
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 3
      - 5
