wandb_config_seq:
  batch_size: 20
  lr: 0.001
  base_dim: 32
  depth: 5
  loss_type: CCE
  importance: 1
  normalize_images: false

wandb_config_bbox_req:
  batch_size: 16
  lr: 0.001
  base_dim: 104
  depth: 6
  batch_norm: True
  loss_type: MSE
  normalize_images: False
  dropout: 0.0

best_model:
  in_channels: 3
  base_dim: 64
  dropout: 0.3
  batch_norm: true
  state_dict_path: models\\best_model_3.pt

paths:
  data_path: 'C:\\my files\\REFUGE'
  train_images_path: 'Training400'
  train_masks_path: 'Annotation-Training400/Disc_Cup_Masks'
  val_images_path: 'REFUGE-Validation400'
  val_masks_path: 'REFUGE-Validation400-GT'
  test_images_path: 'REFUGE-Test400'
  test_masks_path: 'REFUGE-Test-GT'
