wandb_version: 1

base_dim:
  desc: null
  value: 80
batch_norm:
  desc: null
  value: false
batch_size:
  desc: null
  value: 61
dropout:
  desc: null
  value: 0.3
loss_type:
  desc: null
  value: complete_iou
lr:
  desc: null
  value: 6.397178179715562e-06
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687315823.774584
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      - 37
      4: 3.10.11
      5: 0.15.4
      8:
      - 3
      - 5
