wandb_version: 1

base_dim:
  desc: null
  value: 32
batch_norm:
  desc: null
  value: true
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.3
loss_type:
  desc: null
  value: mse
lr:
  desc: null
  value: 0.039806897429840386
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687297547.460688
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 3
      - 5
