wandb_version: 1

base_dim:
  desc: null
  value: 64
batch_norm:
  desc: null
  value: false
batch_size:
  desc: null
  value: 63
dropout:
  desc: null
  value: 0.1
loss_type:
  desc: null
  value: complete_iou
lr:
  desc: null
  value: 5.7150337564899395e-06
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687308015.037758
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 3
      - 5
